version: '3.9'

services:
  django:
    build: .
    command: sh -c "gunicorn --bind 0.0.0.0:8000 config.wsgi"
    volumes:
      - .:/app
      - static_data:/app/static
    expose:
      - 8000
    environment:
      - DATABASE_URL=postgresql://django:admin@db:5432/team_app
      - DEBUG=1
  db:
    image: postgres:14
    volumes:
      - pg_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=team_app
  nginx:
    image: nginx:1.19.8-alpine
    depends_on:
      - django
    ports:
      - "80:80"
    volumes:
      - static_data:/var/www/html/static
      - ./nginx-conf.d:/etc/nginx/conf.d
volumes:
  pg_data:
  static_data:
