# Generated by Django 4.1.7 on 2023-02-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Полное имя")),
                (
                    "name_ru",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Полное имя"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Полное имя"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="staff/", verbose_name="Фото"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "telegram",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Telegram"
                    ),
                ),
                (
                    "instagram",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Instagram"
                    ),
                ),
                (
                    "facebook",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Facebook"
                    ),
                ),
                (
                    "job",
                    models.ManyToManyField(to="jobs.job", verbose_name="Должность"),
                ),
            ],
            options={
                "verbose_name": "Персонал",
                "verbose_name_plural": "Персонал",
            },
        ),
    ]
