# Generated by Django 4.1.7 on 2023-02-24 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "name_ru",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Название"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Название"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "description_ru",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                ("url", models.URLField(verbose_name="URL-адрес")),
                (
                    "client",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Клиент"
                    ),
                ),
                (
                    "client_ru",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Клиент"
                    ),
                ),
                (
                    "client_en",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Клиент"
                    ),
                ),
                (
                    "main_image",
                    models.ImageField(
                        upload_to="works_main_images",
                        verbose_name="Главное изображение",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True, verbose_name="Дата")),
            ],
            options={
                "verbose_name": "Работа",
                "verbose_name_plural": "Работы",
            },
        ),
        migrations.CreateModel(
            name="WorkImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="works_images/", verbose_name="Изображение"
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="works.work",
                        verbose_name="Работа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение работы",
                "verbose_name_plural": "Изображения работы",
            },
        ),
    ]
